# Site settings
title: "Hayoul Kim's Resume"
description: "Information about my works and achivements."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hayoul Kim"
resume_title:                   "Student of Yonsei University Compuser Science"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hayoul1999@yonsei.ac.kr.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-7469-1727"
resume_contact_address:         "03722 서울특별시 서대문구 연세로 50 연세대학교"

resume_header_contact_info:     "03722 서울특별시 서대문구 연세로 50 연세대학교 • 010-7469-1727 • hayoul1999@yonsei.ac.kr"
display_header_contact_info:    "false"

resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
